/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.32).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.CategoryDTO;
import io.swagger.model.CatorgoryListDTO;
import io.swagger.model.CustomerDTO;
import io.swagger.model.CustomerListDTO;
import io.swagger.model.VendorDTO;
import io.swagger.model.VendorListDTO;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2023-08-12T06:05:54.271Z")

@Validated
@Api(value = "api", description = "the api API")
@RequestMapping(value = "")
public interface ApiApi {

    @ApiOperation(value = "createNewCustomer", nickname = "createNewCustomerUsingPOST", notes = "", response = CustomerDTO.class, tags={ "customer-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = CustomerDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/v1/customers",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<CustomerDTO> createNewCustomerUsingPOST(@ApiParam(value = "customerDTO" ,required=true )  @Valid @RequestBody CustomerDTO customerDTO);


    @ApiOperation(value = "Create a new Vendor", nickname = "createNewVendorUsingPOST", notes = "", response = VendorDTO.class, tags={ "vendor-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = VendorDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/v1/vendors",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<VendorDTO> createNewVendorUsingPOST(@ApiParam(value = "vendorDTO" ,required=true )  @Valid @RequestBody VendorDTO vendorDTO);


    @ApiOperation(value = "deleteCustomer", nickname = "deleteCustomerUsingDELETE", notes = "", tags={ "customer-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/v1/customers/{id}",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteCustomerUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "Delete a Vendor", nickname = "deleteVendorUsingDELETE", notes = "", tags={ "vendor-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/v1/vendors/{id}",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteVendorUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllCategories", nickname = "getAllCategoriesUsingGET", notes = "", response = CatorgoryListDTO.class, tags={ "category-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CatorgoryListDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/v1/categories",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<CatorgoryListDTO> getAllCategoriesUsingGET();


    @ApiOperation(value = "getCategoryByName", nickname = "getCategoryByNameUsingGET", notes = "", response = CategoryDTO.class, tags={ "category-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CategoryDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/v1/categories/{name}",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<CategoryDTO> getCategoryByNameUsingGET(@ApiParam(value = "name",required=true) @PathVariable("name") String name);


    @ApiOperation(value = "getCustomerById", nickname = "getCustomerByIdUsingGET", notes = "", response = CustomerDTO.class, tags={ "customer-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CustomerDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/v1/customers/{id}",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<CustomerDTO> getCustomerByIdUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "This will get a list of customers.", nickname = "getListOfCustomersUsingGET", notes = "These are some notes about the API.", response = CustomerListDTO.class, tags={ "customer-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CustomerListDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/v1/customers",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<CustomerListDTO> getListOfCustomersUsingGET();


    @ApiOperation(value = "Get Vendor by Id", nickname = "getVendorByIdUsingGET", notes = "", response = VendorDTO.class, tags={ "vendor-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = VendorDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/v1/vendors/{id}",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<VendorDTO> getVendorByIdUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "View List of Vendors", nickname = "getVendorListUsingGET", notes = "These are some API Notes", response = VendorListDTO.class, tags={ "vendor-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = VendorListDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/v1/vendors",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<VendorListDTO> getVendorListUsingGET();


    @ApiOperation(value = "patchCustomer", nickname = "patchCustomerUsingPATCH", notes = "", response = CustomerDTO.class, tags={ "customer-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CustomerDTO.class),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/v1/customers/{id}",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.PATCH)
    ResponseEntity<CustomerDTO> patchCustomerUsingPATCH(@ApiParam(value = "id",required=true) @PathVariable("id") Long id,@ApiParam(value = "customerDTO" ,required=true )  @Valid @RequestBody CustomerDTO customerDTO);


    @ApiOperation(value = "Update a Vendor Property", nickname = "patchVendorUsingPATCH", notes = "", response = VendorDTO.class, tags={ "vendor-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = VendorDTO.class),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/v1/vendors/{id}",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.PATCH)
    ResponseEntity<VendorDTO> patchVendorUsingPATCH(@ApiParam(value = "id",required=true) @PathVariable("id") Long id,@ApiParam(value = "vendorDTO" ,required=true )  @Valid @RequestBody VendorDTO vendorDTO);


    @ApiOperation(value = "updateCustomer", nickname = "updateCustomerUsingPUT", notes = "", response = CustomerDTO.class, tags={ "customer-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CustomerDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/v1/customers/{id}",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<CustomerDTO> updateCustomerUsingPUT(@ApiParam(value = "id",required=true) @PathVariable("id") Long id,@ApiParam(value = "customerDTO" ,required=true )  @Valid @RequestBody CustomerDTO customerDTO);


    @ApiOperation(value = "Update an existing Vendor", nickname = "updateVendorUsingPUT", notes = "", response = VendorDTO.class, tags={ "vendor-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = VendorDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/v1/vendors/{id}",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<VendorDTO> updateVendorUsingPUT(@ApiParam(value = "id",required=true) @PathVariable("id") Long id,@ApiParam(value = "vendorDTO" ,required=true )  @Valid @RequestBody VendorDTO vendorDTO);

}
