spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_recipe_dev
    username: spring_recipe_dev_user
    password: secret-dev
  sql:
    init:
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true

# Note :: This only needs to be run the once and will generate a schema.sql for us at the project root
# Note :: Take the generated script, open query consoles against the dev + prod databases and run on each
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: schema.sql