spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_recipe_dev
    username: spring_recipe_dev_user
    password: secret-dev
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true