create table category (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, description varchar(255), quantity decimal(19,2), recipe_id bigint, unit_id bigint, primary key (id)) engine=InnoDB;
create table notes (id bigint not null auto_increment, content longtext, recipe_id bigint, primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, cook_mins integer, description varchar(255), difficulty varchar(255), directions longtext, image longblob, prep_mins integer, servings integer, source varchar(255), url varchar(255), notes_id bigint, primary key (id)) engine=InnoDB;
create table recipe_category (recipe_id bigint not null, category_id bigint not null, primary key (recipe_id, category_id)) engine=InnoDB;
create table unit (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FKptcc01xludxytlml6168ea5p7 foreign key (unit_id) references unit (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category (id);
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe (id);

# Note :: this has been auto-generated by Hibernate (see application-dev.yaml)