name: Main

on:
  push:
    branches:
      - 'main'

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./content/07-spring-mvc-web-dev/exercises/recipes
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests and collect coverage
        run: mvn -B test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

# https://github.com/codecov/example-java-maven/blob/main/.github/workflows/ci.yml